### PR TITLE
Add Stickermule as supporting sponsors.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
@winston I added Stickermule under sponsors as well since they are providing in-kind sponsorship for us. Is using the same size fine?

**Comment by winston** [comment]
WIll be good to see a screenshot. :)

**Comment by tgxworld** [comment]
screenshot from 2015-03-26 09 12 31

**Comment by winston** [comment]
@tgxworld Supporting sponsors should ideally be smaller than Associate Sponsors.

I think I have 4 a line for Associate Sponsors, so Supporting Sponsors should probably be around 6 per line. :bow:

**Comment by tgxworld** [comment]
screenshot from 2015-03-27 09 50 16

**Comment by tgxworld** [comment]
Smaller now! haha

**Comment by tgxworld** [comment]
On smaller screens it will have the same width though

**Comment by winston** [comment]
Looks good! 

> On smaller screens it will have the same width though

Then on Line 89 `.col-sm-2.col-sm-offset-5.sponsors--box` you can try `.col-xs-6.col-sm-2.col-sm-offset-5.sponsors--box`?

**Comment by tgxworld** [comment]
screenshot from 2015-03-28 17 20 21
screenshot from 2015-03-28 17 20 32

Done!

**Pull request merged**
