### PR TITLE
Add lightning talk speakers.

### PR DESCRIPTION
**Pull request by tgxworld**
screenshot from 2015-05-03 20 08 21
screenshot from 2015-05-03 20 08 30

### CODE REVIEW

**Comment by tgxworld** [comment]
@winston I did a speed read once to ensure there aren't any spelling mistakes. However, some of the sentences do sound a little weird. Should we correct them?

**Comment by Learnemy** [comment]
Wrong title for Elisha. Also, can change my picture to this?: https://pbs.twimg.com/profile_images/594537360626331648/LEDGHW3d_400x400.png

Thanks!

**Comment by winston** [comment]
@tgxworld Yes. Try to make it sound reasonable. Thanks!

**Comment by winston** [comment]
Looks good by the way!

**Comment by tgxworld** [comment]
@winston Fixed!

**Comment by tgxworld** [comment]
screenshot from 2015-05-03 23 38 56

**Pull request merged**
